apiVersion: apps/v1 # API version for Deployments
kind: Deployment # Defines a Kubernetes Deployment
metadata: # Name of the Deployment
  name: scm-server-deployment 
spec:
  replicas: 3 # Specifies 3 replicas (pods) for this deployment
  selector:
    matchLabels:
      app: scm-server # Selects pods matching this label
  template:
    metadata:
      labels:
        app: scm-server # Labels assigned to pods created by this deployment
    spec:
      volumes:
        - name: server-config # Name of the volume
          configMap:
            name: server-config # Mounts the ConfigMap named 'server-config'
      containers:
        - name: scm-container # Container name
          image: devmaksdev/scm_web_server:latest # Image to use
          env:
            - name: POD_NAME # Sets an environment variable with the pod name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP # Sets an environment variable with the pod's internal IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_UID # Sets an environment variable with the pod's UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_NAMESPACE # Sets an environment variable with the pod's namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: "125m"  # 1/8 of a CPU core (1000m = 1 CPU)
              memory: "256Mi"  # 1/4 of a GiB RAM (1024Mi = 1 GiB)
            requests:
              cpu: "125m"  # Minimum guaranteed CPU allocation
              memory: "256Mi"  # Minimum guaranteed memory allocation
          volumeMounts:
            - name: server-config # Mounts the 'server-config' volume
              mountPath: /home/app/node/config/ # Path inside the container
          ports:
            - containerPort: 8081 # Exposes port 8081 in the container
